name: validate pr

on:
  workflow_call:
    inputs:
      pr_template:
        required: true
        type: string

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull ticket from title
        id: values
        uses: actions/github-script@v6
        env:
          TITLE: ${{ github.event.pull_request.title }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let title = process.env.TITLE;
            const fs = require('fs');
            const pattern = /([^/]+\/)?(PRO-\d{4})(.*)/;
            const matchTitle = pattern.exec(title);
            
            
            const githubHeadRef = process.env.GITHUB_HEAD_REF;
            const githubRef = process.env.GITHUB_REF;
            const branchName = githubHeadRef || githubRef.replace('refs/heads/', '');
            const matchBranch = pattern.exec(branchName);
            
            if (matchTitle) {
              const ticket = matchTitle[2]; // This will contain "PRO-1234"
              let description = matchTitle[3]; // This will contain what comes after "PRO-1234"
              description = description.replace(/^[^a-zA-Z0-9]+/, '');
              console.log("PRO ticket:", ticket);
              console.log("PR description:", description);
              fs.writeFileSync('ticket', ticket);
              fs.writeFileSync('description', description);
            } else if (matchBranch) {
              const ticket = matchBranch[2];
              title = ticket.concat(" ", title);
              fs.writeFileSync('ticket', ticket);
              fs.writeFileSync('title', title);
            }
            
            fs.writeFileSync('title', title);

      - name: Extract variables
        id: extract-variables
        run: |
          ticket=$(cat ticket)
          title=$(cat title)
          description=$(cat description)
          echo "ticket=${ticket}" >> $GITHUB_OUTPUT
          echo "title=${title}" >> $GITHUB_OUTPUT
          echo "description=${description}" >> $GITHUB_OUTPUT
      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.7
        with:
          template: ${{ inputs.pr_template }}
          vars: |
            ticket: "${{ steps.extract-variables.outputs.ticket }}"
            description: "${{ steps.extract-variables.outputs.description }}"
      - name: Update PR Title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          NEW_TITLE="${{ steps.extract-variables.outputs.title }}"
          BODY_TEMPLATE="${{ steps.template.outputs.result }}"
          
          echo "PR_NUMBER: $PR_NUMBER"
          echo "NEW_TITLE: $NEW_TITLE"
          echo "BODY_TEMPLATE: $BODY_TEMPLATE"

          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" \
            -d '{
              "title": ${NEW_TITLE},
            }'
#      - name: Update PR body
#        uses: tzkhan/pr-update-action@v2
#        with:
#          repo-token: "${{ secrets.GITHUB_TOKEN }}"
#          title-template: "${{ steps.extract-variables.outputs.title }}"
#          body-template: "${{ steps.template.outputs.result }}"
#          body-update-action: 'suffix'

